# Generated by Django 5.2.1 on 2025-05-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ourteam_facebook_ourteam_instagram_ourteam_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='twitter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='youtube',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
