# Generated by Django 5.0.6 on 2025-06-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_is_featured_product_is_new_project_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='map_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
