# Generated by Django 5.0.6 on 2025-06-02 22:32

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sitesetting_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('descriptions', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='subsidiaries/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='subsidiaries/banners/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=160, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Subsidiaries',
            },
        ),
        migrations.CreateModel(
            name='SubsidiaryProducts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subsidiaries', to='app.product')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidiary_products', to='app.subsidiary')),
            ],
            options={
                'verbose_name_plural': 'Subsidiary Products',
                'unique_together': {('subsidiary', 'product')},
            },
        ),
    ]
