# Generated by Django 5.0.6 on 2025-06-02 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subsidiary_subsidiaryproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
